import type { BlogPost, DashboardStats, DashboardTask } from "./types";

const author = { id: "me", name: "You", initials: "YO", role: "Author" };

export const initialPosts: BlogPost[] = [
  {
    id: "db-1",
    slug: "getting-started-with-serif",
    title: "Getting Started with Serif",
    subtitle: "A tour of the writing workflow inside Serif.",
    content:
      "This is a draft of your first post. Replace this content with your own writing, or use the AI assistant to generate a draft from an outline.",
    category: "Writing",
    cover: "from-indigo-500 via-violet-500 to-purple-700",
    seoTitle: "Getting Started with Serif",
    seoDescription: "A tour of the writing workflow inside Serif.",
    author,
    status: "published",
    publishedAt: "2026-08-15",
    updatedAt: "2026-08-15",
    readTime: 3,
    views: 1280,
  },
  {
    id: "db-2",
    slug: "draft-better-ideas",
    title: "Draft Better Ideas, Faster",
    subtitle: "How to move from blank page to solid draft in minutes.",
    content:
      "Draft content goes here. Use markdown to structure headings, lists, and code blocks as you write.",
    category: "AI",
    cover: "from-fuchsia-500 via-purple-600 to-violet-800",
    seoTitle: "Draft Better Ideas, Faster",
    seoDescription: "How to move from blank page to solid draft in minutes.",
    author,
    status: "draft",
    publishedAt: "",
    updatedAt: "2026-08-16",
    readTime: 4,
    views: 0,
  },
  {
    id: "db-3",
    slug: "onboarding-new-team-members",
    title: "Onboarding New Team Members",
    subtitle: "A checklist for welcoming writers to your publication.",
    content:
      "A practical checklist for getting new contributors productive on the platform from day one.",
    category: "Productivity",
    cover: "from-emerald-500 via-teal-500 to-cyan-700",
    seoTitle: "Onboarding New Team Members",
    seoDescription: "A checklist for welcoming writers to your publication.",
    author,
    status: "draft",
    publishedAt: "",
    updatedAt: "2026-08-14",
    readTime: 2,
    views: 0,
  },
  {
    id: "db-4",
    slug: "writing-about-technical-topics",
    title: "Writing About Technical Topics",
    subtitle: "Make complex ideas feel effortless for any reader.",
    content:
      "Technical writing is really just clarity under pressure. Start with the outcome, build intuition, then dive into details.",
    category: "Writing",
    cover: "from-sky-500 via-blue-600 to-indigo-700",
    seoTitle: "Writing About Technical Topics",
    seoDescription: "Make complex ideas feel effortless for any reader.",
    author,
    status: "published",
    publishedAt: "2026-08-08",
    updatedAt: "2026-08-09",
    readTime: 6,
    views: 3420,
  },
  {
    id: "db-5",
    slug: "the-case-for-short-posts",
    title: "The Case for Short Posts",
    subtitle: "Respect the reader's time and they'll come back.",
    content:
      "Long-form isn't always better. Short, focused posts can earn more attention per word and fit the cadence of modern readers.",
    category: "Strategy",
    cover: "from-amber-500 via-orange-500 to-rose-600",
    seoTitle: "The Case for Short Posts",
    seoDescription: "Respect the reader's time and they'll come back.",
    author,
    status: "published",
    publishedAt: "2026-07-31",
    updatedAt: "2026-07-31",
    readTime: 2,
    views: 2105,
  },
  {
    id: "db-6",
    slug: "optimize-old-posts",
    title: "Optimizing Your Backlog of Old Posts",
    subtitle: "Your best content is probably already written.",
    content:
      "Refresh, restructure, and re-promote your highest-performing posts. Updating old content is often higher leverage than writing new posts.",
    category: "SEO",
    cover: "from-violet-500 via-indigo-500 to-blue-700",
    seoTitle: "Optimizing Your Backlog of Old Posts",
    seoDescription: "Your best content is probably already written.",
    author,
    status: "draft",
    publishedAt: "",
    updatedAt: "2026-08-05",
    readTime: 3,
    views: 0,
  },
  {
    id: "db-7",
    slug: "newsletter-strategies",
    title: "Newsletter Strategies That Work",
    subtitle: "Turn occasional readers into loyal subscribers.",
    content:
      "Newsletters are the most reliable distribution channel you own. Start with a promise, deliver value weekly, and keep the unsubscribe friction low.",
    category: "Publishing",
    cover: "from-rose-500 via-pink-500 to-fuchsia-600",
    seoTitle: "Newsletter Strategies That Work",
    seoDescription: "Turn occasional readers into loyal subscribers.",
    author,
    status: "published",
    publishedAt: "2026-07-24",
    updatedAt: "2026-07-25",
    readTime: 5,
    views: 1876,
  },
  {
    id: "db-8",
    slug: "a-simple-seo-audit",
    title: "A 20-Minute SEO Audit",
    subtitle: "The highest-impact checks, in order.",
    content:
      "You don't need a consultant to catch the big issues. Run through these checks and fix the ones that move the needle.",
    category: "SEO",
    cover: "from-emerald-500 via-teal-500 to-cyan-700",
    seoTitle: "A 20-Minute SEO Audit",
    seoDescription: "The highest-impact SEO checks, in order.",
    author,
    status: "published",
    publishedAt: "2026-07-17",
    updatedAt: "2026-07-18",
    readTime: 4,
    views: 2980,
  },
  {
    id: "db-9",
    slug: "repurposing-content",
    title: "Repurposing One Post into Ten Assets",
    subtitle: "Stretch every idea across every channel.",
    content:
      "A single great post can become a thread, a video script, a newsletter, and a slide deck. Repurposing multiplies reach without multiplying effort.",
    category: "Publishing",
    cover: "from-amber-500 via-orange-500 to-rose-600",
    seoTitle: "Repurposing One Post into Ten Assets",
    seoDescription: "Stretch every idea across every channel.",
    author,
    status: "draft",
    publishedAt: "",
    updatedAt: "2026-07-29",
    readTime: 3,
    views: 0,
  },
  {
    id: "db-10",
    slug: "weekly-publishing-rhythm",
    title: "Why a Weekly Rhythm Beats Bursts",
    subtitle: "Consistency compounds. Momentum is a feature.",
    content:
      "Bursts of productivity feel good but don't build audiences. A sustainable weekly rhythm does. Here's how to protect it.",
    category: "Productivity",
    cover: "from-sky-500 via-blue-600 to-indigo-700",
    seoTitle: "Why a Weekly Rhythm Beats Bursts",
    seoDescription: "Consistency compounds. Momentum is a feature.",
    author,
    status: "published",
    publishedAt: "2026-07-10",
    updatedAt: "2026-07-10",
    readTime: 3,
    views: 1670,
  },
  {
    id: "db-11",
    slug: "interviews-that-write-themselves",
    title: "Interviews That Write Themselves",
    subtitle: "Great questions produce great posts with almost no effort.",
    content:
      "An interview is a content engine with a co-author. Prepare great questions, transcribe, and shape — the person you interview does half the work.",
    category: "Writing",
    cover: "from-fuchsia-500 via-purple-600 to-violet-800",
    seoTitle: "Interviews That Write Themselves",
    seoDescription: "Great questions produce great posts with almost no effort.",
    author,
    status: "draft",
    publishedAt: "",
    updatedAt: "2026-07-20",
    readTime: 4,
    views: 0,
  },
  {
    id: "db-12",
    slug: "measuring-what-matters",
    title: "Measuring What Matters in Blogging",
    subtitle: "A short guide to the metrics that actually predict growth.",
    content:
      "Not all metrics are equal. Focus on the ones that predict long-term growth: returning readers, shares, and time on page.",
    category: "Strategy",
    cover: "from-indigo-500 via-violet-500 to-purple-700",
    seoTitle: "Measuring What Matters in Blogging",
    seoDescription: "A short guide to the metrics that actually predict growth.",
    author,
    status: "published",
    publishedAt: "2026-07-03",
    updatedAt: "2026-07-04",
    readTime: 5,
    views: 2220,
  },
];

export const initialTasks: DashboardTask[] = [
  {
    id: "task-1",
    title: "Finish draft: 'Draft Better Ideas, Faster'",
    status: "in-progress",
    due: "Aug 20",
  },
  {
    id: "task-2",
    title: "Publish weekly newsletter",
    status: "todo",
    due: "Aug 21",
  },
  {
    id: "task-3",
    title: "Add SEO metadata to old posts",
    status: "todo",
    due: "Aug 23",
  },
  {
    id: "task-4",
    title: "Review analytics for last month",
    status: "done",
    due: "Aug 15",
  },
  {
    id: "task-5",
    title: "Outline three new post ideas",
    status: "todo",
    due: "Aug 25",
  },
];

export const initialStats: DashboardStats = {
  totalPosts: 18,
  drafts: 5,
  monthlyViews: "12.4k",
};

export const dashboardCategories = [
  "AI",
  "Writing",
  "SEO",
  "Strategy",
  "Productivity",
  "Publishing",
];